/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.clientes.vista;

import co.unicauca.clientes.modelo.ClientesDB;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Observable;
/**
 *
 * @author daniel2402
 */
public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements java.util.Observer {

    /**
     * Creates new form GUIEstadisticaPorSexoGrafica
     */
    private Graphics2D g;
    private boolean repaint=false;
    private int hombres=0;
    private int mujeres=0;
    private int total=0;
    public GUIEstadisticaPorSexoGrafica(int h, int v) {
         initComponents();
        setSize(600, 280);
        setLocation(h, v);
        setVisible(true);
        
         
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexoGrafica(600,280).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void update(Observable obs, Object obj) {
        ClientesDB cliDB = (ClientesDB) obs;
        this.setTitle("Profesión: "+ cliDB.getProfesion());
        this.repaint=true;
        this.hombres= cliDB.getTotalHombres();
        this.mujeres=cliDB.getTotalMujeres();
        this.total=cliDB.getClientesPorProfesion().size();
                
        repaint();
        
    }
    public void paint(Graphics g2d){
        g = (Graphics2D) g2d;
        if(this.repaint){
            this.setVisible(false);
          this.setVisible(true);
          g.fillRect(0,0,600,280);
          g.setColor(new Color(28,35,57));
          g.drawRect(300, 50, 60, 250);
          g.drawRect(200, 50, 60, 250);
          float porcentajeM= (this.mujeres*100)/this.total;
          float pixelesM= (porcentajeM*300)/100;
          
          float porcentajeH= (this.hombres*100)/this.total;
          float pixelesH= (porcentajeH*300)/100;
        
          g.fillRect(200, ((Math.round(pixelesH))+50) , 60, 300-((Math.round(pixelesH))+50));
          
          g.fillRect(300, ((Math.round(pixelesM))+50) , 60, 300-((Math.round(pixelesM))+50));
     
        
        
        this.repaint=false;
        } 
        
    }
    public void graficar(){
       
    }
    
   
}
